name: Test

on: ['push', 'pull_request']

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest
    container: node:lts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ./server
        uses: bahmutov/npm-install@v1

      - name: Run Jest
        working-directory: ./server
        run: npm run test:unit