name: Test

on: ['push', 'pull_request']

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest
    container: node:lts

    steps:
      - name: Checkout repository
        working-directory: ./server
        uses: actions/checkout@v3
        
      - name: Install dependencies
        working-directory: ./server
        uses: bahmutov/npm-install@v1

      - name: Run Jest
        working-directory: ./server
        run: npm run test:unit